FROM maven:3-jdk-8-openj9
VOLUME ["$HOME/.m2", "/usr/src/app"]
WORKDIR /usr/src/app
COPY . /usr/src/app
RUN mvn package

FROM java:8
MAINTAINER Kunal Patil <kunalpatil@yahoo.com>

VOLUME /tmp
RUN mkdir /app
COPY --from=0 /usr/src/app/target/boot-commander*.jar /app/boot-commander.jar

EXPOSE 8080

WORKDIR /app
CMD ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/boot-commander.jar"]

