version: '3'
services:
  hsqldb:
    restart: always
    build: ./db/hsqldb
    image: hsqldb-server
    ports:
      - "9001:9001"
    volumes:
      - testcasedb-data:/data

  postgres-db:
    restart: always
    image: postgres:9.6
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: testcasedb
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    volumes:
      - testcasedb-data:/var/lib/postgresql/data

  boot-commander:
    restart: always
    image: boot-commander
    depends_on:
      - postgres-db
    build:
      context: .
      dockerfile: Dockerfile-hub
    ports:
      - "8080:8080"
    environment:
      - DB_HOSTNAME=hsqldb

volumes:
  testcasedb-data:
    external: true
