CREATE OR REPLACE FUNCTION create_testcasedb_schema ()
    RETURNS void as
$func$
BEGIN
   IF EXISTS (SELECT FROM pg_catalog.pg_tables
              WHERE  schemaname = 'PUBLIC'
              AND    tablename  = 'USERS') THEN
      RAISE NOTICE 'Table myschema.mytable already exists.';
   ELSE
    CREATE TABLE USERS (
        ID SERIAL primary KEY,
        USERNAME VARCHAR(100) NOT NULL,
        PASSWORD VARCHAR(100),
        NAME VARCHAR(255),
        EMAIL VARCHAR(255),
        TOKEN VARCHAR(255),
        TOKEN_CREATE_TS TIMESTAMP DEFAULT NOW(),
        TOKEN_ACCESS_TS TIMESTAMP DEFAULT NOW()
    );

    CREATE UNIQUE INDEX IDX_USERS_USERNAME ON USERS (USERNAME);

    CREATE TABLE USER_ROLES (
        ID SERIAL primary KEY,
        USER_ID INTEGER REFERENCES USERS(ID),
        "ROLE" VARCHAR(100)
    );

    CREATE TABLE TEST_CATEGORY (
        ID SERIAL primary KEY,
        NAME VARCHAR(20),
        DESCRIPTION VARCHAR(255)
    );

    CREATE TABLE TESTCASE (
        ID SERIAL primary KEY,
        NAME VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        TEST_CATEGORY_ID INTEGER NOT NULL REFERENCES TEST_CATEGORY(ID),
        REST_URL VARCHAR(255) NOT NULL,
        HTTP_METHOD VARCHAR(10) NOT NULL,
        HTTP_DATA VARCHAR(4000),
        CONTENT_TYPE VARCHAR(50) DEFAULT 'application/json' NOT NULL,
        VALIDATE_OUTPUT INTEGER DEFAULT 0 NOT NULL,
        OUTPUT_TEMPLATE VARCHAR(4000),
        ALLOW_BLANK_OUTPUT INTEGER DEFAULT 0 NOT NULL,
        VALIDATE_TYPE VARCHAR(10)
    );

    CREATE TABLE TESTCASE_INSTANCE (
        ID SERIAL primary KEY,
        NAME VARCHAR(255),
        DESCRIPTION VARCHAR(255),
        TESTCASE_ID INTEGER NOT NULL,
        USER_ID INTEGER NOT NULL,
        VALIDATE_OUTPUT INTEGER DEFAULT 0 NOT NULL,
        OUTPUT_TEMPLATE VARCHAR(4000),
        ALLOW_BLANK_OUTPUT INTEGER DEFAULT 0 NOT NULL,
        VALIDATE_TYPE VARCHAR(10),
        CONSTRAINT FK_TESTINSTANCE_TESTCASE FOREIGN KEY (TESTCASE_ID) REFERENCES TESTCASE(ID),
        CONSTRAINT FK_TESTINSTANCE_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
    );

    CREATE INDEX SYS_IDX_10147 ON TESTCASE_INSTANCE (USER_ID);
    CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10134_10139 ON TESTCASE_INSTANCE (ID);

    CREATE TABLE HOSTS (
        ID SERIAL primary KEY,
        NAME VARCHAR(255),
        HOSTNAME VARCHAR(255) NOT NULL,
        PORT INTEGER NOT NULL,
        SECUREHTTP INTEGER DEFAULT 0 NOT NULL,
        TEST_CATEGORY_ID INTEGER NOT NULL,
        CONSTRAINT FK_HOSTS_TEST_CATEGORY_ID FOREIGN KEY (TEST_CATEGORY_ID) REFERENCES TEST_CATEGORY(ID)
    );
    CREATE INDEX SYS_IDX_10113 ON HOSTS (TEST_CATEGORY_ID);
    CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10102_10107 ON HOSTS (ID);

    CREATE TABLE TESTCASE_RUN (
        ID SERIAL primary KEY,
        TESTCASE_INSTANCE_ID INTEGER NOT NULL,
        HOST_ID INTEGER NOT NULL,
        SUCCESS INTEGER DEFAULT 1 NOT NULL,
        RUN_DATE TIMESTAMP DEFAULT LOCALTIMESTAMP,
        RETURN_CODE INTEGER DEFAULT 0 NOT NULL,
        ERROR VARCHAR(1024),
        "RESULT" VARCHAR(4096),
        CONTENT_TYPE VARCHAR(20),
        CONSTRAINT FK_TESTRUN_HOST FOREIGN KEY (HOST_ID) REFERENCES HOSTS(ID),
        CONSTRAINT FK_TESTRUN_TESTCASEINSTANCE FOREIGN KEY (TESTCASE_INSTANCE_ID) REFERENCES TESTCASE_INSTANCE(ID) ON DELETE CASCADE
    );

    CREATE INDEX SYS_IDX_10171 ON TESTCASE_RUN (TESTCASE_INSTANCE_ID);
    CREATE INDEX SYS_IDX_10173 ON TESTCASE_RUN (HOST_ID);

    CREATE TABLE TESTCASE_VALUES (
        ID SERIAL primary KEY,
        TESTCASE_INSTANCE_ID INTEGER NOT NULL,
        KEY_NAME VARCHAR(255) NOT NULL,
        KEY_VALUE VARCHAR(2048),
        VALUE_TYPE VARCHAR(20),
        CONSTRAINT FK_TESTCASEVALUE_TESTINSTANCE FOREIGN KEY (TESTCASE_INSTANCE_ID) REFERENCES TESTCASE_INSTANCE(ID) ON DELETE CASCADE
    );
    CREATE INDEX SYS_IDX_10157 ON TESTCASE_VALUES (TESTCASE_INSTANCE_ID);
    CREATE UNIQUE INDEX SYS_IDX_SYS_PK_10150_10153 ON TESTCASE_VALUES (ID);

    CREATE TABLE HTTP_HEADERS (
        ID SERIAL primary KEY,
        TEST_CATEGORY_ID INTEGER,
        NAME VARCHAR(255),
        "VALUE" VARCHAR(255),
        TESTCASE_ID INTEGER,
        CONSTRAINT FK_HTTPHEADERS_TESTCATEGORY FOREIGN KEY (TEST_CATEGORY_ID) REFERENCES TEST_CATEGORY(ID)
    );
    CREATE INDEX SYS_IDX_10205 ON HTTP_HEADERS (TEST_CATEGORY_ID);

    CREATE TABLE SCHEDULES (
        ID SERIAL primary KEY,
        NAME VARCHAR(100),
        CRON_EXPR VARCHAR(100),
        HOST_ID INTEGER NOT NULL,
        ACTIVE INTEGER DEFAULT 0 NOT NULL,
        TEST_CATEGORY_ID INTEGER NOT NULL,
        CONSTRAINT FK_SCHEDULE_CATEGORY FOREIGN KEY (TEST_CATEGORY_ID) REFERENCES TEST_CATEGORY(ID) ON DELETE CASCADE,
        CONSTRAINT FK_SCHEDULE_HOST FOREIGN KEY (HOST_ID) REFERENCES HOSTS(ID)
    );
    CREATE INDEX SYS_IDX_10185 ON SCHEDULES (HOST_ID);
    CREATE INDEX SYS_IDX_10187 ON SCHEDULES (TEST_CATEGORY_ID);

    CREATE TABLE SCHEDULED_TESTCASES (
        ID SERIAL primary KEY,
        SCHEDULE_ID INTEGER NOT NULL,
        TESTCASE_INSTANCE_ID INTEGER NOT NULL,
        CONSTRAINT FK_SCHEDULE FOREIGN KEY (SCHEDULE_ID) REFERENCES SCHEDULES(ID) ON DELETE CASCADE,
        CONSTRAINT FK_TESTCASE_INSTANCE FOREIGN KEY (TESTCASE_INSTANCE_ID) REFERENCES TESTCASE_INSTANCE(ID) ON DELETE CASCADE
    );
    CREATE INDEX SYS_IDX_10197 ON SCHEDULED_TESTCASES (SCHEDULE_ID);
    CREATE INDEX SYS_IDX_10199 ON SCHEDULED_TESTCASES (TESTCASE_INSTANCE_ID);

    INSERT INTO USERS VALUES(nextval('users_id_seq'),'admin','$2a$10$sMlE1RPjHYiaLf1T1gtvVu2Y6AtNhX6Ue21Y5PjxYKdCUt29qJSX2','admin','admin@localhost','eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTU0ODYxOTg1OH0.p7ogqPWzoMRRkX8-m4DJR1ZQ8LTWSXRXIf-2sklCWLDLplakpU94inD0bbT_Cz4w7LjjVJPeVn0cGOi9HFuFZw',NULL,NULL);
    insert into user_roles values(nextval('user_roles_id_seq'),1,'SUPERADMIN');

    insert into test_category(id, name, description) values(nextval('test_category_id_seq'), 'COMMANDER', 'Commander Test Cases');

    insert into hosts(id, name, hostname, port, test_category_id ) values(nextval('hosts_id_seq'), 'Boot Commander (Local)', 'localhost', 9090, 1);

    insert into testcase(id, name, description, test_category_id, rest_url, http_method, http_data)
    values(nextval('testcase_id_seq'), 'Get Categories', 'Get a list of all categories', 1, '/boot-commander/categories', 'GET', '');
    insert into testcase_instance(name, description, testcase_id, user_id)
    values('Get Categories', 'Get a list of all categoriest', 1,1 );

END IF;
END
$func$ LANGUAGE plpgsql;


select create_testcasedb_schema();